name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

env:
  TAG: felipebz/zpa-cli:nightly

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --refresh-dependencies

      - name: Assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: copyJdksToCache jreleaserAssemble

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ env.TAG }}

      - name: Analyze demo project on SonarCloud
        run: ./source-test/run-sonar-scanner.sh
        env:
          SONARCLOUD_ORGANIZATION: ${{ secrets.SONARCLOUD_ORGANIZATION }}
          SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

      - if: github.ref == 'refs/heads/main'
        name: Push docker image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.TAG }}

      - if: github.ref == 'refs/heads/main'
        name: Release artifacts
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jreleaserFullRelease
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
